repos:
  - repo: https://github.com/python/black
    rev: stable
    hooks:
    - id: black
      language_version: python3.7
      args: [--line-length=90]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-ast
      - id: check-yaml
      - id: check-toml
      - id: trailing-whitespace
      - id: end-of-file-fixer
  - repo: https://github.com/pre-commit/mirrors-pylint
    rev: v2.3.1
    hooks:
      - id: pylint
        args: [--max-line-length=90]
