name: CI

on:
  push:
    branches: [dev]
  pull_request:
    branches: [master]

jobs:
  pre-commit:
    name: pre-commit
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - uses: actions/cache@v1
        with:
          path: ~/.cache/pre-commit
          key: pre-commit-${{ hashFiles('.pre-commit-config.yaml') }}
      - uses: pre-commit/action@v2.0.0
  tests:
    name: "Python ${{ matrix.python-version }}"
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.7", "3.8"]
        os: [ubuntu-latest, macOS-latest, windows-latest]
    steps:
      - name: Modify env
        if: ${{ matrix.os }} == 'windows-latest'
        env:
          CONDA_DLL_SEARCH_MODIFICATION_ENABLE: 1
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: "${{ matrix.python-version }}"
      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
      - name: Install nox
        run: |
          python -m pip install --upgrade pip
          pip install nox
      - name: Run tests
        run:  nox -s test-${{ matrix.python-version }}
  coverage:
    needs: [tests]
    name: Run coverage
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: 3.7
      - name: Install nox
        run: |
          python -m pip install --upgrade pip
          pip install nox
      - name: Run coverage
        run:  nox -s coverage
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.xml
          flags: PYTHON37
          name: codecov-reports-37
          fail_ci_if_error: true
